var api_Module_Factory = function () {
  var api = {
    name: 'api',
    typeInfos: [{
        localName: 'Response',
        propertyInfos: [{
            name: 'musicFolders',
            typeInfo: 'api.MusicFolders'
          }, {
            name: 'indexes',
            typeInfo: 'api.Indexes'
          }, {
            name: 'directory',
            typeInfo: 'api.Directory'
          }, {
            name: 'genres',
            typeInfo: 'api.Genres'
          }, {
            name: 'artists',
            typeInfo: 'api.ArtistsID3'
          }, {
            name: 'artist',
            typeInfo: 'api.ArtistWithAlbumsID3'
          }, {
            name: 'album',
            typeInfo: 'api.AlbumWithSongsID3'
          }, {
            name: 'song',
            typeInfo: 'api.Child'
          }, {
            name: 'videos',
            typeInfo: 'api.Videos'
          }, {
            name: 'nowPlaying',
            typeInfo: 'api.NowPlaying'
          }, {
            name: 'searchResult',
            typeInfo: 'api.SearchResult'
          }, {
            name: 'searchResult2',
            typeInfo: 'api.SearchResult2'
          }, {
            name: 'searchResult3',
            typeInfo: 'api.SearchResult3'
          }, {
            name: 'playlists',
            typeInfo: 'api.Playlists'
          }, {
            name: 'playlist',
            typeInfo: 'api.PlaylistWithSongs'
          }, {
            name: 'jukeboxStatus',
            typeInfo: 'api.JukeboxStatus'
          }, {
            name: 'jukeboxPlaylist',
            typeInfo: 'api.JukeboxPlaylist'
          }, {
            name: 'license',
            typeInfo: 'api.License'
          }, {
            name: 'users',
            typeInfo: 'api.Users'
          }, {
            name: 'user',
            typeInfo: 'api.User'
          }, {
            name: 'chatMessages',
            typeInfo: 'api.ChatMessages'
          }, {
            name: 'albumList',
            typeInfo: 'api.AlbumList'
          }, {
            name: 'albumList2',
            typeInfo: 'api.AlbumList2'
          }, {
            name: 'randomSongs',
            typeInfo: 'api.Songs'
          }, {
            name: 'songsByGenre',
            typeInfo: 'api.Songs'
          }, {
            name: 'lyrics',
            typeInfo: 'api.Lyrics'
          }, {
            name: 'podcasts',
            typeInfo: 'api.Podcasts'
          }, {
            name: 'internetRadioStations',
            typeInfo: 'api.InternetRadioStations'
          }, {
            name: 'bookmarks',
            typeInfo: 'api.Bookmarks'
          }, {
            name: 'shares',
            typeInfo: 'api.Shares'
          }, {
            name: 'starred',
            typeInfo: 'api.Starred'
          }, {
            name: 'starred2',
            typeInfo: 'api.Starred2'
          }, {
            name: 'error',
            typeInfo: 'api.Error'
          }, {
            name: 'status',
            type: 'attribute'
          }, {
            name: 'version',
            type: 'attribute'
          }]
      }, {
        localName: 'User',
        propertyInfos: [{
            name: 'username',
            type: 'attribute'
          }, {
            name: 'email',
            type: 'attribute'
          }, {
            name: 'scrobblingEnabled',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'adminRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'settingsRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'downloadRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'uploadRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'playlistRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'coverArtRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'commentRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'podcastRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'streamRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'jukeboxRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'shareRole',
            typeInfo: 'Boolean',
            type: 'attribute'
          }]
      }, {
        localName: 'AlbumWithSongsID3',
        baseTypeInfo: 'api.AlbumID3',
        propertyInfos: [{
            name: 'song',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'Users',
        propertyInfos: [{
            name: 'user',
            collection: true,
            typeInfo: 'api.User'
          }]
      }, {
        localName: 'Child',
        propertyInfos: [{
            name: 'id',
            type: 'attribute'
          }, {
            name: 'parent',
            type: 'attribute'
          }, {
            name: 'isDir',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'title',
            type: 'attribute'
          }, {
            name: 'album',
            type: 'attribute'
          }, {
            name: 'artist',
            type: 'attribute'
          }, {
            name: 'track',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'year',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'genre',
            type: 'attribute'
          }, {
            name: 'coverArt',
            type: 'attribute'
          }, {
            name: 'size',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'contentType',
            type: 'attribute'
          }, {
            name: 'suffix',
            type: 'attribute'
          }, {
            name: 'transcodedContentType',
            type: 'attribute'
          }, {
            name: 'transcodedSuffix',
            type: 'attribute'
          }, {
            name: 'duration',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'bitRate',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'path',
            type: 'attribute'
          }, {
            name: 'isVideo',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'userRating',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'averageRating',
            typeInfo: 'Double',
            type: 'attribute'
          }, {
            name: 'discNumber',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'created',
            typeInfo: 'Calendar',
            type: 'attribute'
          }, {
            name: 'starred',
            typeInfo: 'Calendar',
            type: 'attribute'
          }, {
            name: 'albumId',
            type: 'attribute'
          }, {
            name: 'artistId',
            type: 'attribute'
          }, {
            name: 'type',
            type: 'attribute'
          }, {
            name: 'bookmarkPosition',
            typeInfo: 'Long',
            type: 'attribute'
          }]
      }, {
        localName: 'AlbumList2',
        propertyInfos: [{
            name: 'album',
            collection: true,
            typeInfo: 'api.AlbumID3'
          }]
      }, {
        localName: 'InternetRadioStation',
        propertyInfos: [{
            name: 'id',
            type: 'attribute'
          }, {
            name: 'name',
            type: 'attribute'
          }, {
            name: 'streamUrl',
            type: 'attribute'
          }, {
            name: 'homePageUrl',
            type: 'attribute'
          }]
      }, {
        localName: 'Starred2',
        propertyInfos: [{
            name: 'artist',
            collection: true,
            typeInfo: 'api.ArtistID3'
          }, {
            name: 'album',
            collection: true,
            typeInfo: 'api.AlbumID3'
          }, {
            name: 'song',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'Podcasts',
        propertyInfos: [{
            name: 'channel',
            collection: true,
            typeInfo: 'api.PodcastChannel'
          }]
      }, {
        localName: 'InternetRadioStations',
        propertyInfos: [{
            name: 'internetRadioStation',
            collection: true,
            typeInfo: 'api.InternetRadioStation'
          }]
      }, {
        localName: 'Videos',
        propertyInfos: [{
            name: 'video',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'SearchResult',
        propertyInfos: [{
            name: 'match',
            collection: true,
            typeInfo: 'api.Child'
          }, {
            name: 'offset',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'totalHits',
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'ArtistWithAlbumsID3',
        baseTypeInfo: 'api.ArtistID3',
        propertyInfos: [{
            name: 'album',
            collection: true,
            typeInfo: 'api.AlbumID3'
          }]
      }, {
        localName: 'Lyrics',
        propertyInfos: [{
            name: 'content',
            type: 'value'
          }, {
            name: 'artist',
            type: 'attribute'
          }, {
            name: 'title',
            type: 'attribute'
          }]
      }, {
        localName: 'ChatMessages',
        propertyInfos: [{
            name: 'chatMessage',
            collection: true,
            typeInfo: 'api.ChatMessage'
          }]
      }, {
        localName: 'NowPlayingEntry',
        baseTypeInfo: 'api.Child',
        propertyInfos: [{
            name: 'username',
            type: 'attribute'
          }, {
            name: 'minutesAgo',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'playerId',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'playerName',
            type: 'attribute'
          }]
      }, {
        localName: 'SearchResult2',
        propertyInfos: [{
            name: 'artist',
            collection: true,
            typeInfo: 'api.Artist'
          }, {
            name: 'album',
            collection: true,
            typeInfo: 'api.Child'
          }, {
            name: 'song',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'MusicFolder',
        propertyInfos: [{
            name: 'id',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'name',
            type: 'attribute'
          }]
      }, {
        localName: 'SearchResult3',
        propertyInfos: [{
            name: 'artist',
            collection: true,
            typeInfo: 'api.ArtistID3'
          }, {
            name: 'album',
            collection: true,
            typeInfo: 'api.AlbumID3'
          }, {
            name: 'song',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'AlbumID3',
        propertyInfos: [{
            name: 'id',
            type: 'attribute'
          }, {
            name: 'name',
            type: 'attribute'
          }, {
            name: 'artist',
            type: 'attribute'
          }, {
            name: 'artistId',
            type: 'attribute'
          }, {
            name: 'coverArt',
            type: 'attribute'
          }, {
            name: 'songCount',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'duration',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'created',
            typeInfo: 'Calendar',
            type: 'attribute'
          }, {
            name: 'starred',
            typeInfo: 'Calendar',
            type: 'attribute'
          }, {
            name: 'year',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'genre',
            type: 'attribute'
          }]
      }, {
        localName: 'Indexes',
        propertyInfos: [{
            name: 'shortcut',
            collection: true,
            typeInfo: 'api.Artist'
          }, {
            name: 'index',
            collection: true,
            typeInfo: 'api.Index'
          }, {
            name: 'child',
            collection: true,
            typeInfo: 'api.Child'
          }, {
            name: 'lastModified',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'ignoredArticles',
            type: 'attribute'
          }]
      }, {
        localName: 'Index',
        propertyInfos: [{
            name: 'artist',
            collection: true,
            typeInfo: 'api.Artist'
          }, {
            name: 'name',
            type: 'attribute'
          }]
      }, {
        localName: 'Songs',
        propertyInfos: [{
            name: 'song',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'Playlist',
        propertyInfos: [{
            name: 'allowedUser',
            collection: true
          }, {
            name: 'id',
            type: 'attribute'
          }, {
            name: 'name',
            type: 'attribute'
          }, {
            name: 'comment',
            type: 'attribute'
          }, {
            name: 'owner',
            type: 'attribute'
          }, {
            name: '_public',
            typeInfo: 'Boolean',
            attributeName: 'public',
            type: 'attribute'
          }, {
            name: 'songCount',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'duration',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'created',
            typeInfo: 'Calendar',
            type: 'attribute'
          }]
      }, {
        localName: 'PodcastChannel',
        propertyInfos: [{
            name: 'episode',
            collection: true,
            typeInfo: 'api.PodcastEpisode'
          }, {
            name: 'id',
            type: 'attribute'
          }, {
            name: 'url',
            type: 'attribute'
          }, {
            name: 'title',
            type: 'attribute'
          }, {
            name: 'description',
            type: 'attribute'
          }, {
            name: 'status',
            type: 'attribute'
          }, {
            name: 'errorMessage',
            type: 'attribute'
          }]
      }, {
        localName: 'ArtistID3',
        propertyInfos: [{
            name: 'id',
            type: 'attribute'
          }, {
            name: 'name',
            type: 'attribute'
          }, {
            name: 'coverArt',
            type: 'attribute'
          }, {
            name: 'albumCount',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'starred',
            typeInfo: 'Calendar',
            type: 'attribute'
          }]
      }, {
        localName: 'MusicFolders',
        propertyInfos: [{
            name: 'musicFolder',
            collection: true,
            typeInfo: 'api.MusicFolder'
          }]
      }, {
        localName: 'Bookmark',
        propertyInfos: [{
            name: 'entry',
            typeInfo: 'api.Child'
          }, {
            name: 'position',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'username',
            type: 'attribute'
          }, {
            name: 'comment',
            type: 'attribute'
          }, {
            name: 'created',
            typeInfo: 'Calendar',
            type: 'attribute'
          }, {
            name: 'changed',
            typeInfo: 'Calendar',
            type: 'attribute'
          }]
      }, {
        localName: 'ArtistsID3',
        propertyInfos: [{
            name: 'index',
            collection: true,
            typeInfo: 'api.IndexID3'
          }, {
            name: 'ignoredArticles',
            type: 'attribute'
          }]
      }, {
        localName: 'IndexID3',
        propertyInfos: [{
            name: 'artist',
            collection: true,
            typeInfo: 'api.ArtistID3'
          }, {
            name: 'name',
            type: 'attribute'
          }]
      }, {
        localName: 'PlaylistWithSongs',
        baseTypeInfo: 'api.Playlist',
        propertyInfos: [{
            name: 'entry',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'Share',
        propertyInfos: [{
            name: 'entry',
            collection: true,
            typeInfo: 'api.Child'
          }, {
            name: 'id',
            type: 'attribute'
          }, {
            name: 'url',
            type: 'attribute'
          }, {
            name: 'description',
            type: 'attribute'
          }, {
            name: 'username',
            type: 'attribute'
          }, {
            name: 'created',
            typeInfo: 'Calendar',
            type: 'attribute'
          }, {
            name: 'expires',
            typeInfo: 'Calendar',
            type: 'attribute'
          }, {
            name: 'lastVisited',
            typeInfo: 'Calendar',
            type: 'attribute'
          }, {
            name: 'visitCount',
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'Bookmarks',
        propertyInfos: [{
            name: 'bookmark',
            collection: true,
            typeInfo: 'api.Bookmark'
          }]
      }, {
        localName: 'ChatMessage',
        propertyInfos: [{
            name: 'username',
            type: 'attribute'
          }, {
            name: 'time',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'message',
            type: 'attribute'
          }]
      }, {
        localName: 'Artist',
        propertyInfos: [{
            name: 'id',
            type: 'attribute'
          }, {
            name: 'name',
            type: 'attribute'
          }, {
            name: 'starred',
            typeInfo: 'Calendar',
            type: 'attribute'
          }]
      }, {
        localName: 'Starred',
        propertyInfos: [{
            name: 'artist',
            collection: true,
            typeInfo: 'api.Artist'
          }, {
            name: 'album',
            collection: true,
            typeInfo: 'api.Child'
          }, {
            name: 'song',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'AlbumList',
        propertyInfos: [{
            name: 'album',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'PodcastEpisode',
        baseTypeInfo: 'api.Child',
        propertyInfos: [{
            name: 'streamId',
            type: 'attribute'
          }, {
            name: 'description',
            type: 'attribute'
          }, {
            name: 'status',
            type: 'attribute'
          }, {
            name: 'publishDate',
            typeInfo: 'Calendar',
            type: 'attribute'
          }]
      }, {
        localName: 'Error',
        propertyInfos: [{
            name: 'code',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'message',
            type: 'attribute'
          }]
      }, {
        localName: 'JukeboxStatus',
        propertyInfos: [{
            name: 'currentIndex',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'playing',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'gain',
            typeInfo: 'Float',
            type: 'attribute'
          }, {
            name: 'position',
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'License',
        propertyInfos: [{
            name: 'valid',
            typeInfo: 'Boolean',
            type: 'attribute'
          }, {
            name: 'email',
            type: 'attribute'
          }, {
            name: 'key',
            type: 'attribute'
          }, {
            name: 'date',
            typeInfo: 'Calendar',
            type: 'attribute'
          }]
      }, {
        localName: 'Shares',
        propertyInfos: [{
            name: 'share',
            collection: true,
            typeInfo: 'api.Share'
          }]
      }, {
        localName: 'NowPlaying',
        propertyInfos: [{
            name: 'entry',
            collection: true,
            typeInfo: 'api.NowPlayingEntry'
          }]
      }, {
        localName: 'Playlists',
        propertyInfos: [{
            name: 'playlist',
            collection: true,
            typeInfo: 'api.Playlist'
          }]
      }, {
        localName: 'Genres',
        propertyInfos: [{
            name: 'genre',
            collection: true
          }]
      }, {
        localName: 'JukeboxPlaylist',
        baseTypeInfo: 'api.JukeboxStatus',
        propertyInfos: [{
            name: 'entry',
            collection: true,
            typeInfo: 'api.Child'
          }]
      }, {
        localName: 'Directory',
        propertyInfos: [{
            name: 'child',
            collection: true,
            typeInfo: 'api.Child'
          }, {
            name: 'id',
            type: 'attribute'
          }, {
            name: 'parent',
            type: 'attribute'
          }, {
            name: 'name',
            type: 'attribute'
          }, {
            name: 'starred',
            typeInfo: 'Calendar',
            type: 'attribute'
          }]
      }, {
        type: 'enumInfo',
        localName: 'MediaType',
        values: ['music', 'podcast', 'audiobook', 'video']
      }, {
        type: 'enumInfo',
        localName: 'PodcastStatus',
        values: ['new', 'downloading', 'completed', 'error', 'deleted', 'skipped']
      }, {
        type: 'enumInfo',
        localName: 'ResponseStatus',
        values: ['ok', 'failed']
      }],
    elementInfos: [{
        elementName: 'subsonic-response',
        typeInfo: 'api.Response'
      }]
  };
  return {
    api: api
  };
};
module.exports = api_Module_Factory().api;
